// @generated gbsid='form_announcement'
// -----------------------------------------------------------------
// Generated by Xcelerator 
// -----------------------------------------------------------------

import xcel_ssjs_atFunctions;
import xcel_ssjs_atCommands;
import xcel_ssjs_common;


// @generated gbsid='formula_1'
function field_Date_defaultvalue() {
  // @Now
  try {
    return @Now() ;  
  } catch (e) {
    errHandle(e, field_Date_defaultvalue, SEVERITY_LOW, "error") ;
  }
}

