// @generated gbsid='page_employeeMyDrafts'
// -----------------------------------------------------------------
// Generated by Xcelerator 
// -----------------------------------------------------------------

import xcel_ssjs_atFunctions;
import xcel_ssjs_atCommands;
import xcel_ssjs_common;


// @generated gbsid='formula_1'
function embeddedview_1_showsinglecategory() {
  // @UserName
  try {
    return @UserName() ;  
  } catch (e) {
    errHandle(e, embeddedview_1_showsinglecategory, SEVERITY_LOW, "error") ;
  }
}

